#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9162" \
        s6-setuidgid abc /usr/local/bin/apcupsd_exporter -apcupsd.addr "${APC_HOST}:${APC_PORT:-3551}" -telemetry.addr "0.0.0.0:9162"
